### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by arrrrr444** [Rafase282/URL-Shortener#3]
2022-04-13T15:23:02.382897+00:00 heroku[web.1]: State changed from starting to up
2022-04-13T15:56:45.816485+00:00 heroku[web.1]: Idling
2022-04-13T15:56:45.933883+00:00 heroku[web.1]: State changed from up to down
2022-04-13T15:56:47.807549+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2022-04-13T15:56:48.039266+00:00 heroku[web.1]: Process exited with status 143
2022-04-14T01:12:01.337320+00:00 heroku[web.1]: State changed from down to starting
2022-04-14T01:12:02.545651+00:00 heroku[web.1]: Starting process with command `node server.js`
2022-04-14T01:12:05.677510+00:00 app[web.1]: Successfully connected to MongoDB on port 27017.

2022-04-14T01:12:05.689229+00:00 app[web.1]: Node.js listening on port 14689
2022-04-14T01:12:06.031477+00:00 heroku[web.1]: State changed from starting to up
2022-04-14T01:12:21.093118+00:00 heroku[web.1]: Process exited with status 1
2022-04-14T01:12:21.155967+00:00 heroku[web.1]: State changed from up to crashed
2022-04-14T01:12:21.163690+00:00 heroku[web.1]: State changed from crashed to starting
2022-04-14T01:12:20.975803+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/new/http://foo.com:80" host=axs-short.herokuapp.com request_id=fbba0a8a-7993-43be-abeb-94b1835584af fwd="114.79.1.239" dyno=web.1 connect=0ms service=290ms status=503 bytes=0 protocol=https
2022-04-14T01:12:20.965449+00:00 app[web.1]: 
2022-04-14T01:12:20.965508+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:123
2022-04-14T01:12:20.965510+00:00 app[web.1]:     process.nextTick(function() { throw err; });
2022-04-14T01:12:20.965511+00:00 app[web.1]:                                   ^
2022-04-14T01:12:20.966919+00:00 app[web.1]: MongoError: cannot do raw queries on admin in atlas
2022-04-14T01:12:20.966921+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2022-04-14T01:12:20.966922+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:212:36)
2022-04-14T01:12:20.966922+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
2022-04-14T01:12:20.966923+00:00 app[web.1]:     at nextTickCallbackWith0Args (node.js:452:9)
2022-04-14T01:12:20.966934+00:00 app[web.1]:     at process._tickCallback (node.js:381:13)
2022-04-14T01:12:22.020209+00:00 heroku[web.1]: Starting process with command `node server.js`
2022-04-14T01:12:24.975326+00:00 heroku[web.1]: State changed from starting to up
2022-04-14T01:12:24.828338+00:00 app[web.1]: Successfully connected to MongoDB on port 27017.
2022-04-14T01:12:24.846322+00:00 app[web.1]: Node.js listening on port 42684
2022-04-14T01:12:55.493583+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/favicon.ico" host=axs-short.herokuapp.com request_id=847ee581-a5bc-4bff-8ab5-dca21a8fcc7e fwd="114.79.1.239" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2022-04-14T01:11:49.000000+00:00 app[api]: Build started by user ardhixsquerpants@gmail.com
2022-04-14T01:13:15.561282+00:00 app[web.1]: 
2022-04-14T01:13:15.561298+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:123
2022-04-14T01:13:15.561299+00:00 app[web.1]:     process.nextTick(function() { throw err; });
2022-04-14T01:13:15.561299+00:00 app[web.1]:                                   ^
2022-04-14T01:13:15.562102+00:00 app[web.1]: MongoError: cannot do raw queries on admin in atlas
2022-04-14T01:13:15.562103+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2022-04-14T01:13:15.562105+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:212:36)
2022-04-14T01:13:15.562105+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
2022-04-14T01:13:15.562105+00:00 app[web.1]:     at nextTickCallbackWith0Args (node.js:452:9)
2022-04-14T01:13:15.562108+00:00 app[web.1]:     at process._tickCallback (node.js:381:13)
2022-04-14T01:13:15.691470+00:00 heroku[web.1]: Process exited with status 1
2022-04-14T01:13:15.565215+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/new/https://ardhixs.herokuapp.com" host=axs-short.herokuapp.com request_id=e67f42a9-e975-4b17-abe0-ead89e01268c fwd="114.79.1.239" dyno=web.1 connect=0ms service=275ms status=503 bytes=0 protocol=https
2022-04-14T01:13:15.815545+00:00 heroku[web.1]: State changed from up to crashed
2022-04-14T01:12:00.619726+00:00 app[api]: Deploy 44acd053 by user ardhixsquerpants@gmail.com
2022-04-14T01:12:00.619726+00:00 app[api]: Release v4 created by user ardhixsquerpants@gmail.com
2022-04-14T01:13:21.405507+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=axs-short.herokuapp.com request_id=1222bec3-14a8-4b8b-9c9c-37c4dff8b49a fwd="114.79.1.239" dyno=web.1 connect=5001ms service= status=503 bytes= protocol=https
2022-04-14T01:12:01.000000+00:00 app[api]: Build succeeded

**Comment by arrrrr444** [comment]
![Uploading Screenshot_2022-04-14-08-17-08.png…]()
